### PR TITLE
Fix: too much brackets for bash

### PR DESCRIPTION
**Pull request by yanosz**

### CODE REVIEW

**Comment by Rovanion** [comment]
What are you trying to achieve with this pull request? I would recommend this post on SO for a quick overview of what the [[ command in bash does: http://stackoverflow.com/questions/2188199/how-to-use-double-or-single-bracket-parentheses-curly-braces

**Comment by yanosz** [comment]
Did you check that post? It says: 
"he double bracket ([[) does the same thing (basically) as a single bracket, but is a bash builtin."
The problem is, that your script fails in my Debian Wheezy with:  
mediagoblin-celery-worker.sh: 91: mediagoblin-celery-worker.sh: [[: not found
mediagoblin-celery-worker.sh: 91: mediagoblin-celery-worker.sh: [[: not found

If I don't go for the [[ bashism its fine

**Comment by Rovanion** [comment]
Thank you for actually spelling out what should have been in the description of this pull request!

The problem comes about because the script is run in dash, not bash. And since dash only implements POSIX sh the [[ does not exist.

**Comment by yanosz** [comment]
Sorry - I should have explained this earlier -.-
I'm busy atm - so, please don't mind.

**Comment by yanosz** [comment]
No interest in merging, I guess

**Pull request closed without merging**
